// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASuHcx_zooj84hgxLZybFLPYpc_y-LzLY',
    appId: '1:113401398495:web:f823a0a17800ca9db5556a',
    messagingSenderId: '113401398495',
    projectId: 'learnit-7f697',
    authDomain: 'learnit-7f697.firebaseapp.com',
    storageBucket: 'learnit-7f697.firebasestorage.app',
    measurementId: 'G-REPV01F9TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_U_r4TY9R7BuQTciDf2hjNtFpQYwtTyA',
    appId: '1:113401398495:android:fa737fcccc2fe1e4b5556a',
    messagingSenderId: '113401398495',
    projectId: 'learnit-7f697',
    storageBucket: 'learnit-7f697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9Kbm3HQoagub6gf-TYfSKSiA9GcgUR4',
    appId: '1:113401398495:ios:93e5f3ba1c003b94b5556a',
    messagingSenderId: '113401398495',
    projectId: 'learnit-7f697',
    storageBucket: 'learnit-7f697.firebasestorage.app',
    iosBundleId: 'com.example.learnit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9Kbm3HQoagub6gf-TYfSKSiA9GcgUR4',
    appId: '1:113401398495:ios:93e5f3ba1c003b94b5556a',
    messagingSenderId: '113401398495',
    projectId: 'learnit-7f697',
    storageBucket: 'learnit-7f697.firebasestorage.app',
    iosBundleId: 'com.example.learnit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASuHcx_zooj84hgxLZybFLPYpc_y-LzLY',
    appId: '1:113401398495:web:17f344e8ef32e111b5556a',
    messagingSenderId: '113401398495',
    projectId: 'learnit-7f697',
    authDomain: 'learnit-7f697.firebaseapp.com',
    storageBucket: 'learnit-7f697.firebasestorage.app',
    measurementId: 'G-31QYTSGBJB',
  );

}